name: waveform_recorder
description: "A Flutter package for recording audio with real-time waveform visualization, ideal for voice messaging and audio recording features in chat applications."
version: 1.7.0
homepage: https://github.com/csells/waveform_recorder

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  record:
    git: 
      url: https://github.com/Messagenius/record.git
      ref: a1c93d8e4b4e090352fb0f859da037c5d00a5c43
      path: record
  waveform_flutter: ^1.2.0
  web: ^1.1.1

dev_dependencies:
  all_lint_rules_community: ^0.0.41
  flutter_test:
    sdk: flutter
